site_name: GlitchHub - Manuale Utente
copyright: Copyright &copy; 2026 GlitchHub-Team
docs_dir: src/PB/ManualeUtente
site_dir: 'website/ManualeUtente'
site_url: https://glitchhub-team.github.io/ManualeUtente/

nav:
  - Introduzione: index.md
  - Glossario: glossary.md
  - Concetti di dominio:
      - Autenticazione: concetti/autenticazione.md
      - Ruoli utente: concetti/ruoli-utente.md
      - Comandi per gateway e sensori: concetti/comandi.md
      - Profili GATT supportati: concetti/profili.md
      - Microservizi:
          - Gateway: concetti/microservizi/gateway.md
          - Data Consumer: concetti/microservizi/data-consumer.md
          - Dashboard: concetti/microservizi/dashboard.md
          - Observability: concetti/microservizi/observability.md
  - Guide:
      - Gateway:
          - Comandi per gateway e sensori: guide/gateway/comandi.md
          - Creazione ed eliminazione gateway: guide/gateway/create-delete-gateway.md
          - Creazione ed eliminazione sensore: guide/gateway/create-delete-sensor.md
          - Commissioning e decommissioning gateway: guide/gateway/commission-decommission-gateway.md
          - Interruzione e ripresa gateway: guide/gateway/interrupt-resume-gateway.md
          - Interruzione e ripresa sensore: guide/gateway/interrupt-resume-sensor.md
          - Reset e riavvio gateway: guide/gateway/reboot-reset-gateway.md
          - Invio dati IoT: guide/gateway/invio-dati.md
          - Invio messaggio Hello: guide/gateway/hello.md
      - Data Consumer:
          - Ricezione dati IoT: guide/data-consumer/ricezione-dati.md
      - Dashboard Frontend:
          - Login: guide/dashboard-frontend/login.md
      - Dashboard Backend:
          - Login: guide/dashboard-backend/login.md
      - Observability:
          - Configurazione di Grafana: guide/observability/config.md
          - Importare e modificare una dashboard: guide/observability/dashboard.md
          - Metriche del backend: guide/observability/metriche-backend.md
          - Metriche di NATS: guide/observability/metriche-nats.md
          - Metriche di JetStream: guide/observability/metriche-jetstream.md
  - Test:
      - Esecuzione test: test/esecuzione-test.md
  - Installazione:
      - Requisiti:
          - Requisiti Hardware: installazione/requisiti/requisiti-hw.md
          - Requisiti Software: installazione/requisiti/requisiti-sw.md
      - Preparazione del Sistema:
          - Installazione del Software: installazione/preparazione-del-sistema/01-installazione-sw.md
          - Personalizzare la configurazione: installazione/preparazione-del-sistema/02-configurare-ms.md

theme:
  name: material
  language: it
  palette:
    primary: deep-purple
    accent: cyan

plugins:
  - markdownextradata

extra:
  gloss: '<sub>G</sub>'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GlitchHub-Team
    - icon: material/web
      link: https://glitchhub-team.github.io/
