name: Task Progettista
description: Crea una task generica per progettista
title: "Task"
labels: ["documentation", "task-progettista"]
projects: ["GlitchHub-Team/2"]
type: task
body:
- type: textarea
  id: description
  attributes:
    label: Descrizione della Task
