name: Task Programmatore
description: Crea una task generica per programmatore
title: "Task"
labels: ["documentation", "task-programmatore"]
projects: ["GlitchHub-Team/2"]
type: task
body:
- type: textarea
  id: description
  attributes:
    label: Descrizione della Task
