name: Task Verificatore
description: Crea una task generica per verificatore
title: "Task"
labels: ["documentation", "task-verificatore"]
projects: ["GlitchHub-Team/2"]
type: task
body:
- type: textarea
  id: description
  attributes:
    label: Descrizione della Task
